main_resource_group_name="main-resource-group"
location="West Europe"
main_vnet_name="main-vnet"
k8s_subnet_name="k8s-subnet"
k8s_main_name = "k8s-main"
keyvault_name="minecrafthostingcreds"
keyvault_resource_group_name="rg-akv"