apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api
  namespace: argo-cd

spec:
  project: default
  source:
    repoURL: https://github.com/joskapista01/szakdolgozat-api.git
    targetRevision: main
    path: helm/api
    helm:
      version: v3
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false